import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import test, { before } from 'node:test'
import { fileURLToPath } from 'node:url'

import {
  formatInventory,
  inventoryProject,
} from '../skills/retrofit-project/scripts/inventory-project.mjs'
import { clearGeneratedDirectory } from './helpers/generated-directory.mjs'

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const inventoryScript = resolve(repositoryRoot, 'skills/retrofit-project/scripts/inventory-project.mjs')
let projectDirectory

const write = (path, content) => {
  mkdirSync(dirname(resolve(projectDirectory, path)), { recursive: true })
  writeFileSync(resolve(projectDirectory, path), content)
}

// eslint-disable-next-line sonarjs/no-os-command-from-path -- Git from the user's PATH
const git = (...args) => spawnSync('git', args, { cwd: projectDirectory, encoding: 'utf8' })

before(() => {
  projectDirectory = clearGeneratedDirectory('retrofit-legacy')
  write('package.json', JSON.stringify({
    name: 'legacy-app',
    workspaces: ['apps/*'],
    devDependencies: { eslint: '9.0.0', prettier: '3.0.0', typescript: '5.0.0' },
  }))
  write('yarn.lock', '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n')
  write('.husky/pre-commit', 'yarn typecheck\nnpx lint-staged\n')
  write('.eslintrc.json', '{}\n')
  write('apps/web/package.json', JSON.stringify({ name: 'web', dependencies: { next: '14.0.0', react: '18.0.0' } }))
  write('apps/web/tsconfig.json', [
    '{',
    '  // The base enables strict mode.',
    '  "extends": "../../tsconfig.base.json",',
    '  "compilerOptions": { "paths": { "@/*": ["./src/*"], "@shared/*": ["../shared/src/*"] }, },',
    '  "include": ["src/**/*.ts"]',
    '}',
  ].join('\n'))
  write('tsconfig.base.json', '{ "compilerOptions": { "strict": true } }\n')
  write('apps/web/src/page.ts', '// TODO: tracked nowhere\n// TODO(#12): tracked\n// eslint-disable-next-line\nexport const a = 1\n')
  write('apps/web/src/page.test.ts', 'export {}\n')
  write('.env', 'API_URL=http://localhost\n')
  write('.env.example', 'API_URL=\n')
  write('vendor/kit-1.0.0.tgz', 'archive')
  git('init', '--quiet')
  git('add', '.')
})

test('the inventory reports the facts of an existing project and maps them to requirements', () => {
  const inventory = inventoryProject(projectDirectory)

  assert.deepEqual(inventory.workspaces, ['apps/web'])
  assert.deepEqual(inventory.stack, ['Next.js', 'Prettier', 'React'])
  assert.deepEqual(inventory.packageManager, { declared: 'none', lockfile: 'yarn (v1)' })
  assert.deepEqual(inventory.typescript, [{
    path: 'apps/web/tsconfig.json',
    unparsed: false,
    strict: true,
    noUncheckedIndexedAccess: false,
    exactOptionalPropertyTypes: false,
    aliases: [['@/*', ['./src/*']], ['@shared/*', ['../shared/src/*']]],
  }])
  assert.deepEqual(inventory.counts, {
    sourceFiles: 2,
    testFiles: 1,
    eslintDisable: 1,
    debtMarkers: 2,
    trackedDebtMarkers: 1,
  })

  const signals = inventory.signals.map(({ requirement, finding }) => `${requirement}: ${finding}`)
  for (const expected of [
    /^scope: Next\.js is outside the foundation scope/,
    /^DEP-YARN-001: package manager is yarn \(v1\)/,
    /^DEP-ESLINT-001: Prettier is installed/,
    /^DEP-ESLINT-001: legacy \.eslintrc configuration/,
    /^GIT-HOOK-001: pre-commit runs repository-wide checks: yarn typecheck; npx lint-staged$/,
    /^DEP-YARN-001: a Git hook runs npx$/,
    /^GIT-MESSAGE-001: no commit-msg hook/,
    /^CI-GATE-001: no CI pipeline/,
    /^TS-STRICT-001: apps\/web\/tsconfig\.json: strict true, noUncheckedIndexedAccess false$/,
    /^CORE-SUPPRESS-001: 1 eslint-disable directives/,
    /^CORE-DEBT-001: 1 TODO\/FIXME markers without an issue reference$/,
    /^GIT-SECRET-001: tracked environment file: \.env$/,
    /^hygiene: tracked archive: vendor\/kit-1\.0\.0\.tgz$/,
    /^STRUCT-BOUNDARY-001: path aliases @\/\*, @shared\/\*: run dependency-cruiser per workspace/,
    /^DEP-MINIMAL-001: shared\/ is shared through an alias but is not a package/,
  ]) {
    assert.ok(signals.some((signal) => expected.test(signal)), `missing signal ${String(expected)}`)
  }
  assert.ok(!signals.some((signal) => signal.includes('.env.example')), 'an example file is not a secret')
  assert.match(formatInventory(inventory), /^\| GIT-SECRET-001 \| tracked environment file: \.env \|$/m)
})

test('the inventory never writes to the project it reads', () => {
  const before = git('status', '--porcelain').stdout
  const cli = spawnSync(process.execPath, [inventoryScript, '--target', projectDirectory, '--json'], {
    encoding: 'utf8',
  })

  assert.equal(cli.status, 0, cli.stderr)
  assert.equal(JSON.parse(cli.stdout).name, 'legacy-app')
  assert.equal(git('status', '--porcelain').stdout, before)
})
